security:
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext

  providers:
    in_memory:
      memory:
        users:
          admin:
            password: 'docker@2023'
            roles: 'ROLE_ADMIN'
          user:
            password: 'userpass'
            roles: 'ROLE_USER'

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: true
      form_login:
        login_path: login
        check_path: login
      logout:
        path: logout
        target: /

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/user, roles: ROLE_USER }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }